### ISSUE TITLE
Microsoft Reward Bot Issue

### ISSUE THREAD

**Issue by Doaln** [tmxkn1/Microsoft-Reward-Chrome-Ext#31]
Sorry, but I can't see where to post issues with the bot script (not extension). When running the script it worked fine yesterday, but today I get the following error. My friend gets the same error. Again, I apologize for posting here but I can't find where else to post about problems with that script.

```
2022-02-14 11:46:19,870 :: INFO   :: root :: Logging successful.
2022-02-14 11:46:29,199 :: INFO   :: root :: Account summary:
2022-02-14 11:46:29,199 :: INFO   :: root :: Available Points......... 3002
2022-02-14 11:46:29,199 :: INFO   :: root :: PC Search ............... 0/150
2022-02-14 11:46:29,200 :: INFO   :: root :: Mobile Search ........... 0/100
2022-02-14 11:46:29,200 :: INFO   :: root :: Quiz .................... 390/440
2022-02-14 11:46:29,200 :: INFO   :: root :: Punch Card .............. 0/50
2022-02-14 11:46:29,200 :: INFO   :: root :: ----------Work started-----------
2022-02-14 11:46:37,881 :: INFO   :: root :: Number of open offers: 2
2022-02-14 11:46:43,920 :: INFO   :: root :: Link Quest completed
2022-02-14 11:46:44,036 :: ERROR  :: root :: An error has occurred.
Traceback (most recent call last):
  File "D:\Download\Microsoft-Rewards-Bot-2.0.3\ms_rewards.py", line 113, in <module>
    msr.work(flag_pc=parser.pc_mode, flag_mob=parser.mobile_mode,
  File "D:\Download\Microsoft-Rewards-Bot-2.0.3\msreward\msr.py", line 53, in work
    self._work(flag_pc, flag_mob, flag_quiz)
  File "D:\Download\Microsoft-Rewards-Bot-2.0.3\msreward\msr.py", line 60, in _work
    self.worker.do_dashboard(summary)
  File "D:\Download\Microsoft-Rewards-Bot-2.0.3\msreward\worker\worker.py", line 22, in do_dashboard
    self._dashboard.do_dashboard()
  File "D:\Download\Microsoft-Rewards-Bot-2.0.3\msreward\worker\dashboard\dashboard.py", line 35, in do_dashboard
    self._do_offer(link)
  File "D:\Download\Microsoft-Rewards-Bot-2.0.3\msreward\worker\dashboard\dashboard.py", line 51, in _do_offer
    self._goto_offer_link(link)
  File "D:\Download\Microsoft-Rewards-Bot-2.0.3\msreward\worker\dashboard\dashboard.py", line 58, in _goto_offer_link
    link.click()
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: headless chrome=98.0.4758.82)

2022-02-14 11:46:44,040 :: INFO   :: root :: --------------------------------------------------
2022-02-14 11:46:44,044 :: INFO   :: root :: -----------------------End------------------------
2022-02-14 11:46:44,045 :: INFO   :: root :: --------------------------------------------------
```

**Comment by tmxkn1** [comment]
I get this error randomly and it resolves itself the next day or so, or sometimes just by restarting the bot. I haven't got time to look into this yet. 

I've also opened the issue feature on the bot repo.
